import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#47464a",
        "error-container": "#ffdad6",
        "surface-bright": "#fdf8f8",
        "on-tertiary-container": "#88837c",
        "primary-container": "#1b1b1e",
        "tertiary-fixed": "#e8e2d9",
        "on-tertiary": "#ffffff",
        "secondary-container": "#e3e1ec",
        "inverse-surface": "#313030",
        "primary-fixed-dim": "#c8c5ca",
        "on-tertiary-fixed-variant": "#494640",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed-dim": "#cbc6bd",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-tint": "#5f5e61",
        "on-surface-variant": "#47464b",
        "on-primary-container": "#858387",
        "on-surface": "#1c1b1c",
        "surface-container-high": "#ebe7e7",
        "surface-container-lowest": "#ffffff",
        "outline": "#77767b",
        "surface-container-low": "#f7f3f2",
        "tertiary": "#000000",
        "inverse-on-surface": "#f4f0ef",
        "on-tertiary-fixed": "#1d1b16",
        "secondary": "#5d5e66",
        "inverse-primary": "#c8c5ca",
        "surface": "#fdf8f8",
        "primary-fixed": "#e4e1e6",
        "outline-variant": "#c8c5cb",
        "secondary-fixed": "#e3e1ec",
        "on-secondary-container": "#63646c",
        "secondary-fixed-dim": "#c6c5cf",
        "primary": "#000000",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#1b1b1e",
        "on-secondary-fixed-variant": "#46464e",
        "surface-container": "#f1eded",
        "on-secondary-fixed": "#1a1b22",
        "on-error": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-background": "#1c1b1c",
        "tertiary-container": "#1d1b16",
        "surface-dim": "#ddd9d9",
        "background": "#fdf8f8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        "max-width": "1280px",
        md: "16px",
        xs: "4px",
        "margin-desktop": "48px",
        lg: "24px",
        "margin-mobile": "16px",
        gutter: "20px",
        xl: "32px",
        base: "4px",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "label-mono": ["JetBrains Mono"],
        display: ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-mono": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        display: [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [forms],
};
